### ISSUE TITLE
Require msg.value exceeds amount of units wanting to be purchased

### ISSUE THREAD

**Issue by eolszewski** [lmnop/contracts#2]
https://github.com/lmnop/contracts/blob/6a076a6198fbae5308b2ffdf133eacdf0595a712/contracts/PurchaseAlpha.sol#L64

Right now you're checking that it is equal instead of refunding anything extra sent over. People who are bad at math will get rejected and hate you.

**Comment by bpeters** [comment]
@eolszewski  Good point, but probably just keep it simple for now. The contract gets seeded through the dapp, so unless someone is making purchases through the contract directly, there shouldn't be any problems.
