### ISSUE TITLE
Weak Function

### ISSUE THREAD

**Issue by eolszewski** [lmnop/contracts#4]
https://github.com/lmnop/contracts/blob/6a076a6198fbae5308b2ffdf133eacdf0595a712/contracts/PurchaseAlpha.sol#L79

The contract maintains its own balance so this is unnecessary, but why not just have it read like so?

```
function collect() public onlyMultiSig {
  if (msg.sender.send(balance)) {
    balance = 0;
  }
}
```

**Comment by bpeters** [comment]
@eolszewski done!
